version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
        environment:
          TZ: "Europe/London"
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
          version: 18.09.3
      - run:
          name: check updates
          command: |
            sudo npm install -g npm@latest
            sudo npm install -g npm-check-updates
            bash ./tools/check
            npm install
      - run:
          name: test image
          command: |
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            docker build -t wmfs/pizza-build .
            docker pull postgres:9.6.12-alpine
            bash ./tools/test
      - run:
          name: release
          command: bash ./tools/deploy
workflows:
  version: 2
  workflow:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
